language: node_js
node_js:
  - node

CI: true

scripts:
  - npm install
  - npm run test
  - npm run build
  - echo $access_key_id
  - echo $secret_access_key

deploy:
  provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: "versus-mvp"
  skip_cleanup: true
  local_dir: build
  on:
    branch: mvp

branches:
  only:
    - master
    - mvp
    - chris/mvp-1-s3-bucket