# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
    - step:
        name: dev-s3
        deployment: staging   # set to test, staging or production
        # trigger: manual  # uncomment to have a manual step
        image: atlassian/pipelines-awscli
        script:
          - s3 --region "eu-west-1" rm s3://versus-web-dev
          - aws s3 sync --delete . s3://versus-web-dev
    # - step:
    #     name: dev-s3
    #     deployment: production # set to test, staging or production
    #     # trigger: manual  # uncomment to have a manual step
    #     image: atlassian/pipelines-awscli
    #     script:
    #       - s3 --region "eu-west-1" rm s3://versus-web-prod
    #       - aws s3 sync --delete . s3://versus-web-prod
